### ISSUE TITLE
Parsing rules from output

### ISSUE THREAD

**Issue by SamGG** [topepo/C5.0#17]
Hi,
Thanks for this valuable package.
While learning it, I needed some functions to parse the output, extract the rules and compute Fscore to pick the best rule for each class. Should such functions be added to your package or made available separately?
Best,
Samuel

**Comment by ildefons** [comment]
I have the same question. I would like to parse the rules and compute Fscore for each of them.

**Comment by talegari** [comment]
Please check [tidyrules](https://cran.r-project.org/web/packages/tidyrules/vignettes/tidyrules_vignette.html) which provides the rules as R parsable text which can be used to do whatever you want. (see the section titled: 'Use rules inside filter() function.')
