### ISSUE TITLE
Error compiling under Alpine Linux 3.7

### ISSUE THREAD

**Issue by morphy76** [topepo/C5.0#18]
It reports of missing sys/unistd.h (sys/unistd.h: No such file or directory) even if the linux-headers are installed

**Comment by topepo** [comment]
Sorry. I don't think that I can help with this one.

**Comment by bastistician** [comment]
Same problem here, using current Alpine Linux 3.17.
I patch C50 locally with

```diff
diff --git a/src/rc50.c b/src/rc50.c
index b9669a3..6969a6b 100644
--- a/src/rc50.c
+++ b/src/rc50.c
@@ -34,7 +34,7 @@
 #include <signal.h>
 
 #include <sys/time.h>
-#include <sys/unistd.h>
+#include <unistd.h>
 
 #include "redefine.h"
 #include "transform.h"
```

It would be nice if this change could be considered for the next release. Thanks!

**Comment by bastistician** [comment]
@topepo For the current, unpatched CRAN version of C50 (0.1.8), installation on my Alpine Linux system still gives:

```
rc50.c:37:10: fatal error: sys/unistd.h: No such file or directory
   37 | #include <sys/unistd.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
```

`<sys/unistd.h>` is not portable. It does exist on my Ubuntu system, but only to `#include <unistd.h>` anyway.

The patch is trivial (see previous comment): use `#include <unistd.h>` as specified by POSIX.
It would be great if this could be fixed. Thanks!

**Comment by dtscd** [comment]
I agree that the fix would be easy for the src.

Until that happens, the build env can also be patched by running:
```sh
mkdir -p /usr/include/sys && ln -s /usr/include/unistd.h /usr/include/sys/unistd.h
```
