### ISSUE TITLE
Error in plot and then plot() does not match summary()

### ISSUE THREAD

**Issue by RaymondBalise** [topepo/C5.0#22]
When I try to plot a tree I am getting an "Error in if (!n.cat[i]) { : missing value where TRUE/FALSE needed" error. Here is the code:

```
credit <- read.csv ("https://raw.githubusercontent.com/dataspelunking/MLwR/master/Machine%20Learning%20with%20R%20(2nd%20Ed.)/Chapter%2005/credit.csv",
                  row.names = NULL, 
                  stringsAsFactors = TRUE)

set.seed(123)
train_sample <- sample(1000, 900)
credit_train <- credit[train_sample, ]

library(C50)
credit_model <- C5.0(credit_train[-c(17)], credit_train$default)
plot(credit_model)
```
Is there some way to plot this tree?

When I drop one of the variables the tree is drawn but the output does not match the summary():

```
credit_model2 <- C5.0(credit_train[-c(14,17)], credit_train$default)
summary(credit_model2)
pdf("rplot.pdf", height=30, width = 100) ; plot(credit_model2); dev.off()
```
In particular, the top split in the tree is based on a factor with 4 levels called checking_balance. The summary says the split is on:

checking_balance in {> 200 DM,unknown}: no (412/50) 
checking_balance in {< 0 DM,1 - 200 DM}:

But the picture shows a split on > 200 DM vs unknown and there is no mention of the <0 or 1-200 DM factor levels in the split.

Is the plot broken or am I not understanding the output?

**Comment by mvculp** [comment]
Thank you for pointing out these bugs. 

The latest Development version on github fixes these issues, and you should be able to plot the trees correctly, now.  Please feel free to test it out.
