### ISSUE TITLE
Setting a parameter for max-tree depth

### ISSUE THREAD

**Issue by sumaiyah** [topepo/C5.0#27]
Hi 

Thanks for this great package! 

I'm using it to extract rules from DNNs, however the work I am basing my project off of used C4.5 and stipulated that 

'only binary splits are allowed and the trees have a maximum depth of ten nodes'

I was wondering if there was a way to set the maximum depth of the decision tree built?

Thanks,
Sumaiyah :)

**Comment by topepo** [comment]
There isn't a limit to the depth (that I'm aware of). C5.0 doesn't have an option for tree depth; that is mostly determined by the `minCases` and `CF` arguments in the control function.
