### ISSUE TITLE
Error when plotting

### ISSUE THREAD

**Issue by acnb** [topepo/C5.0#3]
On my machine the iris example works perfectly (thanks for the plot function), however my own model (https://www.dropbox.com/sh/y10x87p292nfjth/AABG3O57rOhI11POvWLMW6aZa?dl=0) fails to plot with the error message:

Error in 1:dim(a17)[1] : argument of length 0

**Comment by zhupengjia** [comment]
got the same error

**Comment by topepo** [comment]
This should be resolved in the current version
