### ISSUE TITLE
makeDataFile fails for large data sets

### ISSUE THREAD

**Issue by kzenstratus** [topepo/C5.0#4]
Error in paste(apply(x, 1, paste, collapse = ","), collapse = "\n") :    result would exceed 2^31-1 bytes

When creating a tree using C5.0(x,y), where x has around 3 million observations, 100 columns, I believe that the above snippet is creating a string that exceeds the memory limit for strings.

**Comment by topepo** [comment]
There's not much I can do about it right now. From [this page](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Memory-limits.html): 

> "The number of bytes in a character string is limited to `2^31 - 1 ~ 2*10^9`, which is also the limit on each dimension of an array."
