### ISSUE TITLE
When plotting a C5.0 tree, error in model.frame

### ISSUE THREAD

**Issue by rakeshnbabu** [topepo/C5.0#8]
Please see the below code which reproduces an error when plotting a C5.0 tree in R version 3.4.1 (2017-06-30) x86_64-w64-mingw32 on Windows 7:

```
data(iris)
library(C50)
myFormula <- as.formula("Species ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width")
myTree <- C5.0(myFormula, data=iris)
plot(myTree)

Error in `[.data.frame`(mf, rsp) : undefined columns selected
```

The problem exists in model.frame.C5.0 on line 16 and 17. I believe the code attempts to determine the response variable. When the response variable is corrected in the browser by stepping through to line 17 and running 
```
rsp <- "Species"
```
, the plot generates as expected.

**Comment by topepo** [comment]
This should be fixed in the github version if you would like to test.

**Comment by lethalbrains** [comment]
+1
